name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - uses: actions/checkout@v2
        with:
          ref: main
          path: main
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          path: rucio
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r main/requirements.sphinx.txt
      - name: Build docs
        run: |
          cd main
          chmod 755 build-sphinx-docs.sh 
          ./build-sphinx-docs.sh
    
